server:
  port: 9003
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9999/eureka
  instance:
    prefer-ip-address: true

spring:
  application:
    name: project-qa
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.2.129:3306/myproject_qa?characterEncoding=utf-8
    username: root
    password: root123
  jpa:
    database: MySQL
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

jwt:
  config:
    key: qa
    expire: 3600000
