server:
  port: 9006
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9999/eureka
  instance:
    prefer-ip-address: true

spring:
  application:
    name: project-comments
  data:
    mongodb:
      host: 192.168.2.129
      database: myproject_comments


  redis:
    host: 192.168.2.129



